#!/bin/bash

# File: lastlog
# Description: Quickly output the latest Peabot log file to the console.
# Created: May 6, 2017
# Author: Matt Mumau

CURRENT_DIR=$(pwd);

cd /var/log/peabot
LATEST_LOG=$(ls -t1 |  head -n 1)

cat $LATEST_LOG

cd $CURRENT_DIR