#!/bin/bash

# File: rebuild
# Description: Shell script for completely rebuilding and reinstalling Peabot.
# Created: May 6, 2017
# Author: Matt Mumau

if [ "$EUID" -ne 0 ]; then 
    echo "Peabot rebuild must be run as root."
    exit
fi

make full_uninstall
make clean
make
make install